### ISSUE TITLE
Export scrambles the order of the exported items

### ISSUE THREAD

**Issue by rkoe** [danny0838/firefox-scrapbook#166] opened 2016-12-10 13:33 UTC
When using "Import/Export...", and then using drag'n'drop to move a whole bunch of items from the tree on the left to the Import/Export-field on the right, the order of the items is scramled. That's expecially bad when trying to move data from one scrapbook to another.

Example: For demonstration, I've stored 9 websites and renamed them to 1..9, and then drag'n'dropped them to the Import-/Export-field:

- Scrapbook order: 1, 2, 3, 4, 5, 6, 7, 8, 9
- Import/Export order: 2, 8, 3, 9, 4, 7, 1, 5, 6

The only way to prevent this, is to *manually drag'n'drop every single item separately*, but thats a lot of work and unreliable, if you have many items.

**Comment by danny0838** [comment] 2016-12-10 13:39
I cannot reproduce it according to your description. Could you provide the ScrapBook X and Firefox version you use and a few screenshots illustrating the steps you actually do?

**Comment by rkoe** [comment] 2016-12-10 14:05
Scapbook X: 1.13.4
Firefox: 45.5.1
OS: Debian GNU/Linux 8

Steps to reproduce here:

- create a new scrapbook (I called it 'test')
- open http://example.com/ and store it 9 times in the new scapbook
- rename the stored pages to 1..9
- open Import/Export...
- select all entries on the left, and drag'n'drop them to the right.

I've also made some screenshots. Since the github-file-upload does not work, you can find them on:
http://www.simple-is-better.org/scrapbook/

**Comment by danny0838** [comment] 2016-12-10 16:46
Your steps seem to be quite normal but I never had this problem on Windows or Ubuntu with a wide range of Fx and SBX versions using similar steps. Could you try this on a fresh new portable Firefox to see if it still happen?

**Comment by rkoe** [comment] 2016-12-10 22:23
Now, I've tried it with fresh installations of:

- Firefox 45.5.1-esr
- Firefox 50.0.2
- Firefox "firefox-45.3.0esr" from NixOS

I've always used a new profile (./firefox --ProfileManager --no-remote), then installed ScrapBook X as only addon, restarted firefox (as requested after the addon-installation), and then reproduced the steps above.
Result: Always scrambled.

(By the way: Maybe the scrambling depends somehow on how the saved pages are named. When I named them "1 2 3 4 5 6 7 8 9", I reproducibly got "2 8 3 9 4 7 1 5 6", after renaming them to "11 22 33 44 55 6 7 8 9", I got "33 8 22 55 9 7 44 11 6". But this could also be some other effect, I don't know.)

**Comment by danny0838** [comment] 2016-12-12 13:15
Do you have another computer and possibly try this on Scapbook X 1.13.4, Firefox: 50.0.2 on Windows?

**Comment by rkoe** [comment] 2016-12-15 20:35
First: Thank you very much for your quick replies.

I have now tested it, with a different computer and:

- Debian 8, Firefox 50.1.0
- Debian-live-CD with included Firefox 45.3.0 (debian-live-8.6.0-amd64-xfce-desktop.iso)
- NixOS-live-CD, firefox 50.0.2 (nixos-graphical-16.09.1229.f52eaf4-x86_64-linux.iso + nix-env -i firefox-50.0.2)

I don't use Windows, so no test on Windows.

Result: Always scambled.

The log-window shows the entries in the right order (e.g.: Export (1/9) 1; Export (2/9) 2; Export (3/9) 3; ...), but the exported order does not match this log-order. On the live-CDs, the order was reversed at the first try
(9 8 7 6 5 4 3 2 1), but after saving one more page and exporting again, it was scrambled differently.

**Comment by danny0838** [comment] 2016-12-24 14:31
Sorting of items in the exported folder depends on lastModifiedTime of the exported folder. However, it seems that [the nsIFile.lastModifiedTime](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIFile) API  of Firefox on *nix does not get lastModifiedTime to the precition of fractional seconds, and thus items that are exported in the same second cannot be sorted properly.

We cannot fix this issue easily since it's an issue of Firefox core. We'd seek for an alternative if there is one available.

**Comment by danny0838** [comment] 2017-12-06 03:31
Fixed in 1.14.0 series by adding support of export time recording.

**Closed by danny0838** 2017-12-06 03:31 UTC
Labels: bug, help wanted
