### ISSUE TITLE
Firefox unsupported CSS declarations are removed during capture

### ISSUE THREAD

**Issue by Menti** [danny0838/firefox-scrapbook#86] opened 2016-02-18 10:50 UTC
Steps to reproduce: 
1. Capture a page with CSS prefixes for browsers other than Firefox. For example: https://www.html5andbeyond.com/css-filter-effects-applying-them-to-images/
2. Export the captured page to disk.
3. Open the page with Chrome or other browser.
4. All the CSS declarations with non-Firefox prefixes have been stripped from the CSS and the page does not display correctly in other browsers (in the example: 'filter' is kept, but '-webkit-filter' is not, so the archived page does not look correctly like the online page).

This is an issue if you want to use Scrapbook X to archive pages for general use by other people who may use other browsers, which was my case today (I wanted to archive a company site in order to show it to a possible client, from a tablet, even without connection).

I guess the reason is that Scrapbook X must be getting the CSS from Firefox, already processed by the browser, instead of directly getting it from its URL. Is there any possible solution?

**Comment by mseliger** [comment] 2016-02-18 21:49
Hello Menti,
i've tried to reproduce your problem, but I don't see a difference whether I opened a saved page in Scrapbook in Chrome, Firefox or e.g. in Qupzilla. Could you add a screenshot, where the problem is?
Greetings, Maria

**Comment by danny0838** [comment] 2016-02-19 17:07
@Menti You are right. This is a somehow critical issue. Your analysis is correct, that Firefox has removed all style entries that it doesn't support, and thus ScrapBook cannot get full styles via the API Firefox provided.

To fix this problem, we'd probably have to write a CSS parser in our own, which is a damn complicated work and we probably cannot make it in a short time.

Currently a workaround is to capture a page with "reorganize styles" unchecked, which will simply download all unprocessed css files. Problems could happen, though, when a CSS contains `@import` or `@font-face`, the imported CSS or fonts would not be captured.

**Comment by danny0838** [comment] 2016-08-20 04:07
Add an option to rewrite CSS links only when capturing in [1.13.0rc2](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0rc2), which may solve the issue for general use cases.

**Comment by danny0838** [comment] 2016-08-26 10:22
This issue is probably fixed in [1.13.0](https://github.com/danny0838/firefox-scrapbook/releases/tag/1.13.0). Report it if still break in any case.

**Closed by danny0838** 2016-08-26 10:22 UTC
Labels: bug
