### ISSUE TITLE
not working correctly anymore in waterfox

### ISSUE THREAD

**Issue by MrIcedTea** [danny0838/firefox-scrapbook#284] opened 2019-11-24 09:16 UTC
hi,
in waterfox only a few pages are able to be saved using latest scrapbook, like wikipedia works (most times) github dose not. I am using scrapbook 1.14.7 with waterfox 2019.10 (64-bit) on debian.

i dont see any way to get log files (please help me out on this) but the outcome is an incomplete saved page with just some css and images without even a index.dat:

![image](https://user-images.githubusercontent.com/36527562/69492454-54008600-0ea3-11ea-9056-e2f3bfda063e.png)

Maybe the first step to fix this could be to create index.dat before everything else (so that you get at least a list of the urls you tried to save (im total lost now)) and create a logfile within the ScrapBook directory

thanks for any help in advance

**Comment by Michaelsy** [comment] 2019-11-24 13:35
Are you aware that there are two different branches of Waterfox 2019.10? Maybe this could be relevant to your problem. https://www.waterfox.net/blog/waterfox-2019.10-release-download/

**Comment by danny0838** [comment] 2019-11-25 16:06
@MrIcedTea Seems like a duplicate of #235. Please check whether your Waterfox has e10s disabled (at about:support).

Revised the README for more details about this.

**Closed** 2020-04-28 13:13 UTC
