### ISSUE TITLE
old issue #254 persisting: Waterfox - new pages are not saved properly

### ISSUE THREAD

**Issue by GuitarTab** [danny0838/firefox-scrapbook#281] opened 2019-05-16 16:57 UTC
Installed ScrapBook X in Waterfox and pointed it to my old ScrapBook directory from Firefox pre-57.

All the old saved web pages are displayed fine; but I can't add new ones. New folders are created, like *20190516184338*, but they don't contain an *index.html*-file, and nothing appears in the ScrapBook sidebar. A *ScrapBook: Save Completed*-message **DOES** appear, though.

**Comment by danny0838** [comment] 2019-05-16 17:14
Please provide the version of your OS, Waterfox, ScrapBook X, the webpage URL you attempt to save, and the save options.

**Comment by GuitarTab** [comment] 2019-05-16 17:44
Thanks for your swift reply, appreciated!

I'm on High Sierra, Waterfox and ScrapBook are the latest versions.

I created a completely new profile for Waterfox, didn't change any settings, and installed *scrapbook_x-1.14.6-fx.xpi*. In ScrapBook, likewise, I didn't change any of the default settings.

I tried to save various websites, e.g. google.com ... ;)

**Comment by danny0838** [comment] 2019-05-17 00:05
Seems to be a duplicate of #235. Disable multiprocess in thr options (via the "Enable Multi-Process Waterfox") as ScrapBook X is not compatible with e10s.

**Closed by danny0838** 2019-05-17 00:05 UTC
